### PR TITLE
Updated Angular Scaffolding

### PR DESCRIPTION
**Pull request by tmarzeion**
This PR updates Angular project scaffolding.

Changelog:
1. Yeoman is now downloading more OWA dependencies:
- angular-ui-router -> for page routing
- openmrs-contrib-uicommons -> to use openmrs components
2. Yeoman is copying another files when Angular is chosen instead of jQuery

Notes:
I think there should be radio-button/switch logic instead of checkbox logic inside choosing library, because:
- its not good idea to use jQuery along with Angular.
- package.json will throw parsing exception, because there is no `,` symbol after jQuery dependency declaration (see code below):
`<% if(includeJQuery === true) { %> "jquery": "^2.2.0" <% } %>`
`<% if(includeAngular === true) { %> "angular": "^1.5.3" <% } %>`

Check it out and tell me what do You think :)

### CODE REVIEW

**Comment by rkorytkowski** [comment]
@psbrandt, could you please consider releasing generator with that change soonish? We are about to publish a new video tutorial on using uicommons components for building OWAs and it would be great to have the proper scaffolding for AngularJS integrated into the generator prior to that so others can test it out.

**Comment by psbrandt** [comment]
@rkorytkowski, I'm happy to do this release, but let me add you as a collaborator to the package on npm. That way you will also be able to perform releases. What's your username there?

**Comment by rkorytkowski** [comment]
It's rkorytkowski
Thanks!

**Comment by psbrandt** [comment]
No problem. Once the build is passing, I'll review, and if it's all good I'll merge and publish `v0.2.0`.

**Comment by tmarzeion** [comment]
@psbrandt  @rkorytkowski 
I've corrected tests, travis passes now.
(Codacy thinks that strings needs to be doublequoted, but whole general.js file convention is singlequoted)

**Comment by psbrandt** [comment]
Thanks @tmarzeion, I'll take a look as soon as I can.

**Comment by tmarzeion** [comment]
@psbrandt What's up with Your review? :)

**Comment by psbrandt** [comment]
Sorry about the delay @tmarzeion. When I try to scaffold an app that uses jQuery, I get the following:

```sh
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the OpenMRS  |
   `---------´   |  Open Web App generator. |
    ( _´U`_ )    |   Answer the following   |
    /___A___\    |     questions to help    |
     |  ~  |     |    scaffold your app.    |
   __'.___.'__   '--------------------------'
 ´   `  |° ´ Y `

? What is your app name? demo1
? What is your app description? demo one
? What libraries would you like to include? jQuery
? What type of server are you running locally? Standalone
? What URL will your app be served from? http://localhost:8082/openmrs-standalone/owa/demo1/index.html
? What is the path of your local Open Web Apps directory? /Users/pascal/Downloads/openmrs-standalone-2.3.1/appdata/owa
? What is your GitHub username? psbrandt
? What will the GitHub repo URL be? https://github.com/psbrandt/openmrs-owa-demo1

events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/pascal/workspace/generator-openmrs-owa/app/templates/jquery/index.html
    at EditionInterface.exports._copySingle (/Users/pascal/workspace/generator-openmrs-owa/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/pascal/workspace/generator-openmrs-owa/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/pascal/workspace/generator-openmrs-owa/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:12:8)
    at module.exports.generators.Base.extend.writing.html (/Users/pascal/workspace/generator-openmrs-owa/app/index.js:313:17)
    at Object.<anonymous> (/Users/pascal/workspace/generator-openmrs-owa/node_modules/yeoman-generator/lib/base.js:436:25)
    at /Users/pascal/workspace/generator-openmrs-owa/node_modules/yeoman-generator/node_modules/run-async/index.js:24:25
    at /Users/pascal/workspace/generator-openmrs-owa/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:516:17)
```
I guess [this line](https://github.com/tmarzeion/generator-openmrs-owa/commit/a3909498a1108193b358929dfb7c316ebd78f48f#diff-2018087f584c4398b5c3a23fc0e5f9dbR314) should be:
```js
this.templatePath('html/jquery/index.html')
```
instead of:
```js
this.templatePath('jquery/index.html')
```
Perhaps consider adding a test for this?

**Comment by tmarzeion** [comment]
@psbrandt 
Okay, I've improved tests to check not only Angular, but also JQuery.
PS. When choosing Angular/JQuery, there is no checkbox anymore

**Comment by psbrandt** [comment]
Okay, I'll have another look soon. I did notice that running the build is taking quite a while:

```sh
demo1 npm run build

> demo1@0.1.0 build /Users/pascal/workspace/scratch/yt5/demo1
> npm run clean && webpack --progress --colors --mode=production --target=web


> demo1@0.1.0 clean /Users/pascal/workspace/scratch/yt5/demo1
> rimraf dist && rimraf coverage*

Hash: 13bad8c4bdbd40243ff4
Version: webpack 1.13.1
Time: 220772ms
              Asset       Size  Chunks             Chunk Names
  app.bundle.min.js     1.2 MB       0  [emitted]  app
  css.bundle.min.js    4.38 kB       1  [emitted]  css
   vendor.bundle.js     169 kB       2  [emitted]  vendor
         index.html  451 bytes          [emitted]
    manifest.webapp  360 bytes          [emitted]
img/omrs-button.png    3.19 kB          [emitted]
   [0] multi vendor 28 bytes {2} [built]
    + 19 hidden modules
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
distributable has been zipped! size: 706152
```

Is it also taking you **220772ms** to build, or is this just some issue with my environment?

**Comment by tmarzeion** [comment]
@psbrandt Build time must be caused by Your's environment issues, because on my computer it takes about 10-15 seconds.
External code is now in `vendor.bundle.js`, thanks to @PawelGutkowski for ÜBER HELP on that :)

**Comment by psbrandt** [comment]
Okay thanks @tmarzeion. I'll take another look as soon as I can.

**Comment by psbrandt** [comment]
If I create an app that uses jQuery, it isn't actually used in the template. Please change the JavaScript template to:

```js
import jquery from 'jquery';

(function () {
  'use strict';
  document.addEventListener("DOMContentLoaded", function(event) {
    console.log('demozz OpenMRS Open Web App Started.');
    console.log('jQuery version: ' + jquery.fn.jquery);
  });
}());
```

Also, the OpenMRS icon link is broken. It needs to be changed from `href="../"` to `href="../../"`.

If I create an app that uses Angular, I see the following in the JavaScript console when the app loads:

```
WARNING: Tried to load angular more than once.
```

The apps are deployed differently depending on if you build the ZIP and upload it to OpenMRS manually, or if you use `npm run build:deploy` or `npm run watch`. If you manually upload the ZIP, the version number is in the filename and path. I think we already discussed this and decided it was best not to have the version in the path. Right @rkorytkowski?

Building the ZIP and then manually uploading it falls over pretty hard for an Angular app:

```sh
vendor.bundle.js:1 Uncaught Error: [$injector:modulerr] Failed to instantiate module main due to:
Error: [$injector:modulerr] Failed to instantiate module demoNG due to:
Error: [$injector:modulerr] Failed to instantiate module home due to:
Error: [$injector:unpr] Unknown provider: e
```

☝Does this also happen for you?

**Comment by tmarzeion** [comment]
> App that uses jQuery, it isn't actually used in the template
- Done
> OpenMRS icon link is broken
- Done
> WARNING: Tried to load angular more than once
- This one is caused by openmrs-contrib-uicommons that tries to load angular by itself, it not bad at all, ask @rkorytkowski for details if You want :)
> not to have the version in the path
- Done (by changing created `*.zip` file's name)
> Building the ZIP and then manually uploading it falls over pretty hard for an Angular app
Angular couldn't load app, because of minify process made dependency injections useless. I've added ng-annotate webpack plugin dependency and used it to make sure that every injection (ngInject) is done

**Comment by tmarzeion** [comment]
@psbrandt Did You have chance to take a look on that? :hamburger:

**Pull request merged**
