### PR TITLE
OMRSJS-19 : Fixed build failure in case of app name with white-spaces

### PR DESCRIPTION
**Pull request by Ankitkumar94**
issue link :  https://issues.openmrs.org/browse/OMRSJS-19

### CODE REVIEW

**Comment by psbrandt** [comment]
It would be better to remove _all_ characters that aren't allowed in AngularJS module names. Also, make sure the resulting case matches the OpenMRS AngularJS [style guide](https://wiki.openmrs.org/display/projects/JavaScript+Ecosystem#JavaScriptEcosystem-AngularJS).

**Comment by Ankitkumar94** [comment]
@psbrandt  There is no particular naming convention mentioned in the John Papa style guide for modules naming. So, should i try to use camelCase instead ?? (though it will be somewhat complicated to implement)

**Comment by psbrandt** [comment]
My personal preference is [PascalCase](https://en.wikipedia.org/wiki/PascalCase) (obviously), but as long as the [naming guidelines](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#naming) are met, that's fine.

**Comment by Ankitkumar94** [comment]
PR updated ! I have implemented "your name" case  :)
If there are any further changes to be done in this PR, kindly let me know !!

**Comment by Ankitkumar94** [comment]
@psbrandt  Sir, i have updated the pr, could u please review it ?

**Pull request merged**
