### PR TITLE
Added components from ui-commons library

### PR DESCRIPTION
**Pull request by Ankitkumar94**
** Used the "openmrs-contrib-uicommons" library to add some of its components into the Openmrs OWA generator
** After adding the ui-commons library support, also ensured that the angularjs best practices are to be followed
** Best practices are followed by using the ES6 classes and components (converted the components of ui-commons library into es6 classes and used arrow functions) and also by deprecating the use of "ng-controllers".

### CODE REVIEW

**Comment by Ankitkumar94** [comment]
@psbrandt  Hii !!
Just a kind reminder for this PR ! (whenever you have time)  :)

**Comment by psbrandt** [comment]
I generated a blank AngularJS app and pushed the code [here](https://github.com/psbrandt/openmrs-owa-testapp). I'll make my comments there.

Also, if @djazayeri or @rkorytkowski want to take a look, they can just look at [the generated app](https://github.com/psbrandt/openmrs-owa-testapp) instead of having to mess with the generator.

**Comment by Ankitkumar94** [comment]
Sir I guess u have generated the app from this current PR. Actually, in this PR, I have only introduced components from the ui-commons library. I haven't directly accessed the openmrsRest module to design components.
In this repository (https://github.com/Ankitkumar94/owa-testApp), you will find the patientSearch component. So, I guess you should go through this repo !!

**Comment by psbrandt** [comment]
Right. The app I generated was to review this PR, not to debug the `openmrsRest` issue. I will use your [owa-testApp](https://github.com/Ankitkumar94/owa-testApp) repo for that.

**Comment by psbrandt** [comment]
See my first three comments on this commit [here](https://github.com/psbrandt/openmrs-owa-testapp/commit/c7b97af832f12bedc9a6ea79b24ab4ffff7eedfa).

**Comment by Ankitkumar94** [comment]
sir you can now test the app through this : https://github.com/Ankitkumar94/owa-testApp

I have corrected the translate component as well as the patient search component. Each component present there at the homepage is now working !! I will commit all the new changes here (in this PR) in a while. 
Currently looking for the error you mentioned there in the comments section !

**Comment by Ankitkumar94** [comment]
Closing due to new PR  i.e  https://github.com/psbrandt/generator-openmrs-owa/pull/30

**Pull request closed without merging**
